### ISSUE TITLE
无法提交新的url

### ISSUE THREAD

**Issue by vra** [dev-topics-only/lobsters#2]
在账户激活后，提交新的链接时报下面的错，问下是什么原因呢，谢谢。
![image](https://user-images.githubusercontent.com/5562395/210259472-eaa0b140-7fb3-45f6-831b-5ab7942f8c1c.png)

**Comment by PipecraftNet** [comment]
@vra 

【新用户】无法提交【新的域名】的文章。这是防止新用户恶意提交不适宜的网站的一个设计。

请参考 [FAQ](https://dto.pipecraft.net/s/rulyfs)。

https://ppwwyyxx.com/blog/2022/Demystify-RAM-Usage-in-Multiprocess-DataLoader/
这篇文章的域名已经添加了，现在可以提交了。
